name: Chocolatey Release Pipeline
on:
  push:
    branches:
      - main

jobs:
  Release-Chocolatey-Package:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: 📦 Pack Chocolatey Package
        run: choco pack --version 1.6.0-alpha4
      - name: 🔐 Set Chocolatey API-KEY
        run: choco apikey --api-key ${{ secrets.API_KEY }} -source https://push.chocolatey.org/
      - name: 🚀 Push Chocolatey Package
        run: choco push -source https://push.chocolatey.org/
